default_platform(:ios)

platform :ios do
  lane :prod do
    build_app(
      scheme: "Streakable",
      configuration: "Release",
      export_options: {
        provisioningProfiles: {
          "tokyo.kumabook.Streakable" => "f4aa852a-0570-450b-867b-03fde12aac7f",
        }
      }
   )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      team_id: '1180571',
    )
  end
end
